"""attempting to locate this character varying(3) error

Revision ID: 0db7c60574f9
Revises: 903b8bce5f0c
Create Date: 2024-07-17 10:35:26.357725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db7c60574f9'
down_revision = '903b8bce5f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

    # ### end Alembic commands ###
