"""second attempt at recent db update

Revision ID: 1864b1a64432
Revises: 11f94b7aaf63
Create Date: 2024-06-24 10:32:39.861865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1864b1a64432'
down_revision = '11f94b7aaf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('markup_variable')

    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('ccreated_at')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_2')
        batch_op.drop_column('address_1')

    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ccreated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markup_variable', sa.INTEGER(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_by')

    op.create_table('_alembic_tmp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_number', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('address_1', sa.VARCHAR(), nullable=True),
    sa.Column('address_2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_accounts'),
    sa.UniqueConstraint('company_name', name='uq_accounts_company_name')
    )
    # ### end Alembic commands ###
