"""updating tracks_exact_length attribute datatype to boolean

Revision ID: 4abf2da72bcb
Revises: 0da105420b54
Create Date: 2024-08-16 05:31:06.887222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abf2da72bcb'
down_revision = '0da105420b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.alter_column('tracks_exact_length',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.alter_column('tracks_exact_length',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
