"""address_1 required

Revision ID: 4d2d7c40d8e0
Revises: 5623cbfa2caf
Create Date: 2024-07-19 13:59:45.280941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2d7c40d8e0'
down_revision = '5623cbfa2caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_number', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('address_1', sa.VARCHAR(), nullable=True),
    sa.Column('address_2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_accounts'),
    sa.UniqueConstraint('account_number', name='uq_accounts_account_number'),
    sa.UniqueConstraint('company_name', name='uq_accounts_company_name')
    )
    # ### end Alembic commands ###
