"""account_number set to unique=true, models.py

Revision ID: 5623cbfa2caf
Revises: d71c69f725df
Create Date: 2024-07-19 13:55:00.531190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5623cbfa2caf'
down_revision = 'd71c69f725df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_accounts_account_number'), ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_accounts_account_number'), type_='unique')

    # ### end Alembic commands ###
