"""adding price columns to screenconfigurations table models.py

Revision ID: 629cd187e569
Revises: 95f19fb10af0
Create Date: 2024-08-08 16:07:48.132869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629cd187e569'
down_revision = '95f19fb10af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motor_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tube_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('housing_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tracks_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hem_bar_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fabric_charge', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('powder_charge', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.drop_column('powder_charge')
        batch_op.drop_column('fabric_charge')
        batch_op.drop_column('hem_bar_charge')
        batch_op.drop_column('tracks_charge')
        batch_op.drop_column('housing_charge')
        batch_op.drop_column('tube_charge')
        batch_op.drop_column('motor_charge')

    # ### end Alembic commands ###
