"""updated relationship in quote to match screenconfigurations table relationship

Revision ID: 7e23db0012a2
Revises: 8e708df18cb0
Create Date: 2024-08-04 08:11:33.973011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e23db0012a2'
down_revision = '8e708df18cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(), nullable=True),
    sa.Column('product_title', sa.VARCHAR(), nullable=True),
    sa.Column('product_description', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='fk_configurations_quote_id_quotes'),
    sa.PrimaryKeyConstraint('id', name='pk_configurations')
    )
    # ### end Alembic commands ###
