"""new screenconfigurations model added

Revision ID: 8e708df18cb0
Revises: 1864b1a64432
Create Date: 2024-08-04 08:04:36.537668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e708df18cb0'
down_revision = '1864b1a64432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenconfigurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('complete_unit', sa.String(), nullable=True),
    sa.Column('housing', sa.String(), nullable=True),
    sa.Column('side_track', sa.String(), nullable=True),
    sa.Column('hem_bar', sa.String(), nullable=True),
    sa.Column('fabric', sa.String(), nullable=True),
    sa.Column('motor_tube', sa.String(), nullable=True),
    sa.Column('unit_width', sa.String(), nullable=True),
    sa.Column('unit_height', sa.String(), nullable=True),
    sa.Column('housing_tube_size', sa.String(), nullable=True),
    sa.Column('housing_type', sa.String(), nullable=True),
    sa.Column('motor_type', sa.String(), nullable=True),
    sa.Column('motor_side', sa.String(), nullable=True),
    sa.Column('power_chord', sa.String(), nullable=True),
    sa.Column('retention_type', sa.String(), nullable=True),
    sa.Column('retention_cap_color', sa.String(), nullable=True),
    sa.Column('left_retention', sa.String(), nullable=True),
    sa.Column('right_retention', sa.String(), nullable=True),
    sa.Column('tracks_exact_length', sa.String(), nullable=True),
    sa.Column('hem_bar_type', sa.String(), nullable=True),
    sa.Column('hem_cap_color', sa.String(), nullable=True),
    sa.Column('pile_brush_style', sa.String(), nullable=True),
    sa.Column('fabric_type', sa.String(), nullable=True),
    sa.Column('fabric_selection', sa.String(), nullable=True),
    sa.Column('seam_location', sa.String(), nullable=True),
    sa.Column('seam_location_num', sa.Integer(), nullable=True),
    sa.Column('zipper_color', sa.String(), nullable=True),
    sa.Column('usable_fab_width', sa.Integer(), nullable=True),
    sa.Column('rotate_fabric', sa.String(), nullable=True),
    sa.Column('color_collection', sa.String(), nullable=True),
    sa.Column('frame_color', sa.String(), nullable=True),
    sa.Column('list_price', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_screenconfigurations_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenconfigurations'))
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('markup_variable',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_quotes_quote_number'), ['quote_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quotes_quote_number'), type_='unique')
        batch_op.alter_column('markup_variable',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.drop_table('screenconfigurations')
    # ### end Alembic commands ###
