"""removing relationships and serialization to test building out each model on it own and adding to db

Revision ID: 8f48a5b10298
Revises: cfeffa5e9e2a
Create Date: 2024-06-11 11:50:07.368093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f48a5b10298'
down_revision = 'cfeffa5e9e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_account_id_accounts', type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotes_account_id_accounts', type_='foreignkey')
        batch_op.drop_constraint('fk_quotes_customer_id_customers', type_='foreignkey')
        batch_op.drop_constraint('fk_quotes_configuration_id_configurations', type_='foreignkey')
        batch_op.drop_column('configuration_id')
        batch_op.drop_column('account_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('configuration_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quotes_configuration_id_configurations', 'configurations', ['configuration_id'], ['id'])
        batch_op.create_foreign_key('fk_quotes_customer_id_customers', 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key('fk_quotes_account_id_accounts', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_customers_account_id_accounts', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###
