"""blocking users in seed, updated phone to string type in Customer

Revision ID: 903b8bce5f0c
Revises: 7f5dbab60c1b
Create Date: 2024-07-17 10:01:33.854092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903b8bce5f0c'
down_revision = '7f5dbab60c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
