"""quick update to __repr__ in screenconfiguration

Revision ID: 95f19fb10af0
Revises: 7e23db0012a2
Create Date: 2024-08-04 08:13:32.076790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f19fb10af0'
down_revision = '7e23db0012a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usable_fabric_width', sa.Integer(), nullable=True))
        batch_op.drop_column('usable_fab_width')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usable_fab_width', sa.INTEGER(), nullable=True))
        batch_op.drop_column('usable_fabric_width')

    # ### end Alembic commands ###
