"""update to order attributes to match structure

Revision ID: b1a5a4e178bc
Revises: 52d16d80ab27
Create Date: 2024-10-27 09:50:12.486268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a5a4e178bc'
down_revision = '52d16d80ab27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('terms_conditions', sa.String(), nullable=True))
        batch_op.drop_column('orderDate')
        batch_op.drop_column('orderNumber')
        batch_op.drop_column('termsAndConditions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termsAndConditions', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('orderNumber', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('orderDate', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('terms_conditions')
        batch_op.drop_column('created_at')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
