"""updated quote and config relationship and table; quote can have many configuations, a configuration will have only one quote

Revision ID: c2ef947d9429
Revises: d613bc372707
Create Date: 2024-06-11 20:44:13.012721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ef947d9429'
down_revision = 'd613bc372707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_configurations_quote_id_quotes'), 'quotes', ['quote_id'], ['id'])

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotes_configuration_id_configurations', type_='foreignkey')
        batch_op.drop_column('configuration_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuration_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quotes_configuration_id_configurations', 'configurations', ['configuration_id'], ['id'])

    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_configurations_quote_id_quotes'), type_='foreignkey')
        batch_op.drop_column('quote_id')

    # ### end Alembic commands ###
