"""adding orders_id to screenconfig table

Revision ID: d30f1b221589
Revises: 368029128770
Create Date: 2024-09-30 11:01:00.430101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30f1b221589'
down_revision = '368029128770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_screenconfigurations_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenconfigurations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_screenconfigurations_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
