"""config table and screenconfigs table updates

Revision ID: d5a450921f5c
Revises: 1864b1a64432
Create Date: 2024-08-27 13:05:35.616894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a450921f5c'
down_revision = '1864b1a64432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenconfigurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('complete_unit', sa.Boolean(), nullable=True),
    sa.Column('housing', sa.Boolean(), nullable=True),
    sa.Column('side_track', sa.Boolean(), nullable=True),
    sa.Column('hem_bar', sa.Boolean(), nullable=True),
    sa.Column('fabric', sa.Boolean(), nullable=True),
    sa.Column('motor_tube', sa.Boolean(), nullable=True),
    sa.Column('unit_width', sa.Float(), nullable=True),
    sa.Column('unit_height', sa.Float(), nullable=True),
    sa.Column('housing_tube_size', sa.String(), nullable=True),
    sa.Column('housing_type', sa.String(), nullable=True),
    sa.Column('motor_type', sa.String(), nullable=True),
    sa.Column('motor_side', sa.String(), nullable=True),
    sa.Column('power_chord', sa.String(), nullable=True),
    sa.Column('motor_charge', sa.Float(), nullable=True),
    sa.Column('tube_charge', sa.Float(), nullable=True),
    sa.Column('housing_charge', sa.Float(), nullable=True),
    sa.Column('retention_type', sa.String(), nullable=True),
    sa.Column('retention_cap_color', sa.String(), nullable=True),
    sa.Column('tracks_exact_length', sa.Boolean(), nullable=True),
    sa.Column('tracks_charge', sa.Float(), nullable=True),
    sa.Column('hem_bar_type', sa.String(), nullable=True),
    sa.Column('hem_cap_color', sa.String(), nullable=True),
    sa.Column('pile_brush_style', sa.String(), nullable=True),
    sa.Column('hem_bar_charge', sa.Float(), nullable=True),
    sa.Column('fabric_type', sa.String(), nullable=True),
    sa.Column('fabric_selection', sa.String(), nullable=True),
    sa.Column('zipper_color', sa.String(), nullable=True),
    sa.Column('fabric_charge', sa.Float(), nullable=True),
    sa.Column('color_collection', sa.String(), nullable=True),
    sa.Column('frame_color', sa.String(), nullable=True),
    sa.Column('powder_charge', sa.Float(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_screenconfigurations_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenconfigurations'))
    )
    op.drop_table('configurations')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('markup_variable',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_quotes_quote_number'), ['quote_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quotes_quote_number'), type_='unique')
        batch_op.alter_column('markup_variable',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.INTEGER(), nullable=True),
    sa.Column('product_title', sa.VARCHAR(), nullable=True),
    sa.Column('product_description', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='fk_configurations_quote_id_quotes'),
    sa.PrimaryKeyConstraint('id', name='pk_configurations')
    )
    op.drop_table('screenconfigurations')
    # ### end Alembic commands ###
