"""updated User model

Revision ID: da28c6bc2d0c
Revises: 1864b1a64432
Create Date: 2024-07-17 07:23:04.189734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da28c6bc2d0c'
down_revision = '1864b1a64432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_quotes_quote_number'), ['quote_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quotes_quote_number'), type_='unique')

    # ### end Alembic commands ###
