"""Model.py: added nullable=false to Account model

Revision ID: e29b2b5d6962
Revises: a32a8f0754e8
Create Date: 2024-07-18 15:32:28.432209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29b2b5d6962'
down_revision = 'a32a8f0754e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
